In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [3]:
file_path = "movies.csv"
movies_df = pd.read_csv(file_path)
file_path2 = "ratings_sample.csv"
rating_df = pd.read_csv(file_path2)
movies_df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [5]:
movies_df['year'] = movies_df.title.str.extract("(\(\d\d\d\d\))", expand=False)
movies_df['year'] = movies_df['year'].str.extract("(\d\d\d\d)", expand=False)
movies_df['title'] = movies_df['title'].str.replace('(\(\d\d\d\d\))', '', regex=True)
movies_df['title'] = movies_df['title'].apply(lambda x: x.strip())
movies_df.head()

,movieId,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji,Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men,Comedy|Romance,1995
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II,Comedy,1995

In [7]:
movies_df = movies_df.drop('genres', axis=1)
movies_df.head()

   movieId                        title  year
0        1                    Toy Story  1995
1        2                      Jumanji  1995
2        3             Grumpier Old Men  1995
3        4            Waiting to Exhale  1995
4        5  Father of the Bride Part II  1995

In [9]:
rating_df.head()

   userId  movieId  rating   timestamp
0       1      169     2.5  1204927694
1       1     2471     3.0  1204927438
2       1    48516     5.0  1204927435
3       2     2571     3.5  1436165433
4       2   109487     4.0  1436165496

In [11]:
rating_df = rating_df.drop('timestamp', axis=1)
rating_df.head()

   userId  movieId  rating
0       1      169     2.5
1       1     2471     3.0
2       1    48516     5.0
3       2     2571     3.5
4       2   109487     4.0

In [90]:
if 'userId' in rating_df.columns and rating_df['userId'].dtype != 'int64':
    rating_df['userId'] = pd.to_numeric(rating_df['userId'], errors='coerce')
    rating_df.dropna(subset=['userId'], inplace=True)
    rating_df['userId'] = rating_df['userId'].astype('int64')

if 'movieId' in rating_df.columns and rating_df['movieId'].dtype != 'int64':
    rating_df['movieId'] = pd.to_numeric(rating_df['movieId'], errors='coerce')
    rating_df['movieId'] = rating_df['movieId'].astype('int64')

if 'movieId' in movies_df.columns and movies_df['movieId'].dtype != 'int64':
    movies_df['movieId'] = pd.to_numeric(movies_df['movieId'], errors='coerce')
    movies_df['movieId'] = movies_df['movieId'].astype('int64')

## Collaborative Filtering

In [93]:
user_Id = 2
userInput = rating_df[rating_df['userId'] == user_Id]
inputMovies = pd.merge(userInput, movies_df, on='movieId')
inputMovies

   userId  movieId  rating         title  year
0       2     2571     3.5   Matrix, The  1999
1       2   109487     4.0  Interstellar  2014
2       2   112552     5.0      Whiplash  2014
3       2   112556     4.0     Gone Girl  2014

In [95]:
inputMovies = inputMovies.drop('year', axis=1)
inputMovies.head()

   userId  movieId  rating         title
0       2     2571     3.5   Matrix, The
1       2   109487     4.0  Interstellar
2       2   112552     5.0      Whiplash
3       2   112556     4.0     Gone Girl

### the users who has seen the same movies

In [98]:
userSubset = rating_df[rating_df['movieId'].isin(inputMovies['movieId'].tolist())]
userSubset.head(10)

     userId  movieId  rating
3         2     2571     3.5
4         2   109487     4.0
5         2   112552     5.0
6         2   112556     4.0
105       4     2571     4.0
195       5     2571     2.5
202       5   112552     4.5
203       5   112556     4.5
252       7   109487     5.0
356      11     2571     4.5

In [100]:
userSubset.shape

(14689, 3)

In [102]:
userSubsetGroup = userSubset.groupby(['userId'])

In [104]:
userSubsetGroup.get_group(1130)

        userId  movieId  rating
104530    1130     2571     2.0

In [110]:
userSubsetGroup = sorted(userSubsetGroup, key=lambda x: len(x[1]), reverse=True)
userSubsetGroup[0:3]

[((2,),
     userId  movieId  rating
  3       2     2571     3.5
  4       2   109487     4.0
  5       2   112552     5.0
  6       2   112556     4.0),
 ((115,),
         userId  movieId  rating
  11171     115     2571     5.0
  11222     115   109487     4.0
  11224     115   112552     3.5
  11225     115   112556     5.0),
 ((128,),
         userId  movieId  rating
  12405     128     2571     3.5
  12410     128   109487     5.0
  12412     128   112552     4.0
  12413     128   112556     5.0)]

## Similarity of users to input user

In [125]:
from scipy.stats import pearsonr
pearsoncorrelationdict = {}
for user_tuple, user_rating in userSubsetGroup :
    user_name = user_tuple[0]
    
    commonMovies = inputMovies[inputMovies['movieId'].isin(user_rating['movieId'])]
    
    userRatingSorted = user_rating.sort_values(by='movieId')
    commonMoviesSorted = commonMovies.sort_values(by='movieId')

    if len(commonMoviesSorted) == 0 :
        pearsoncorrelationdict[user_name] = 0
        continue

    inputRating = commonMoviesSorted['rating'].tolist()
    userRatingList = userRatingSorted[userRatingSorted['movieId'].isin(commonMoviesSorted['movieId'])]['rating'].tolist()

    if len(inputRating) > 1:
        corr, _ = pearsonr(inputRating, userRatingList)
        pearsoncorrelationdict[user_name] = corr
    else:
       pearsoncorrelationdict[user_name] = 0

In [127]:
pearsoncorrelationdict

{2: 0.9999999999999998,
 115: -0.838870492807861,
 128: 0.04415107856883482,
 176: 0.13245323570650436,
 237: -0.05263157894736839,
 383: -0.13245323570650436,
 409: 0.7894736842105261,
 474: -0.32444284226152503,
 598: 0.5129891760425771,
 632: 0.5739640213948523,
 815: 0.0,
 820: 0.3823595564509362,
 1011: -0.8992288030258968,
 1040: -0.9233805168766386,
 1209: -0.64888568452305,
 1337: -0.760885910252682,
 1502: 0.20751433915982237,
 1660: -0.973328526784575,
 1669: nan,
 1848: -0.3077935056255462,
 2149: 0.838870492807861,
 2169: 0.7492686492653552,
 2253: 0.6882472016116852,
 2274: 0.17492785713532985,
 2452: -0.20751433915982237,
 2604: -0.029867384554474852,
 2726: -0.13245323570650436,
 2788: -0.4842001247062522,
 2814: 0.32444284226152503,
 2824: -0.13245323570650436,
 3119: -0.6622661785325219,
 3130: -0.7059732072369207,
 3309: 0.6882472016116852,
 3508: -0.6882472016116852,
 3577: 0.13245323570650436,
 3699: 0.64888568452305,
 3734: -0.512989176042577,
 3768: -0.6622661785325219,
 3781: -0.6225430174794669,
 3825: -0.32444284226152503,
 3962: 0.22941573387056174,
 4143: -0.32444284226152503,
 4208: 0.05263157894736839,
 4278: -0.3458572319330373,
 4428: -0.8651809126974002,
 4577: 0.9271726499455306,
 4733: 0.13245323570650436,
 4987: -0.22941573387056174,
 5133: -0.14933692277237473,
 5152: 0.029867384554474852,
 5227: nan,
 5336: -0.973328526784575,
 5520: -0.9271726499455306,
 5588: 0.4842001247062522,
 5630: -0.22941573387056174,
 5911: 0.20751433915982237,
 5965: 0.4736842105263157,
 6157: 0.13245323570650436,
 6190: -0.20751433915982237,
 6199: 0.22941573387056174,
 6268: 0.4842001247062522,
 6276: 0.54611868127275,
 6527: 0.15789473684210525,
 6567: 0.7346969999683856,
 6601: -0.32444284226152503,
 6640: -0.8992288030258968,
 6654: 0.9271726499455306,
 6701: -0.6614568092371103,
 7014: -0.760885910252682,
 7108: 0.13245323570650436,
 7278: 0.9446104285307814,
 7315: 0.6622661785325219,
 7371: -0.13245323570650436,
 7482: 0.7233393492970543,
 7550: 0.13245323570650436,
 7736: 0.6622661785325219,
 7909: -0.3077935056255462,
 7944: 0.6882472016116852,
 8239: -0.40406667373059707,
 8494: -0.3458572319330373,
 8606: -0.64888568452305,
 8851: 0.35043832202523123,
 8928: -0.6622661785325219,
 9033: 0.32444284226152503,
 9431: 0.5536258194734202,
 9552: 0.32444284226152503,
 9733: nan,
 9797: -0.6882472016116852,
 9880: -0.05564148840746574,
 10088: 0.22941573387056174,
 10096: -0.9810229431759452,
 10167: -0.973328526784575,
 10231: 0.8992288030258968,
 10278: 0.9365858115816941,
 10298: 0.760885910252682,
 10532: -0.64888568452305,
 10541: -0.22941573387056174,
 10580: -0.32444284226152503,
 10610: 0.13245323570650436,
 10776: nan,
 10996: 0.973328526784575,
 11035: 0.760885910252682,
 11071: 0.13245323570650436,
 11098: 0.4842001247062522,
 11180: 0.15789473684210525,
 11260: 0.13245323570650436,
 12197: 0.9271726499455306,
 12286: -0.9271726499455306,
 12354: -0.20751433915982237,
 12542: 0.0,
 12582: -0.3458572319330373,
 12728: 0.870571500132014,
 13047: 0.13245323570650436,
 13081: 0.13245323570650436,
 13504: -0.15789473684210525,
 13577: 0.4842001247062522,
 13773: 0.7181848464596078,
 14588: -0.15789473684210525,
 14727: 0.8992288030258968,
 14883: -0.3458572319330373,
 15005: -0.20751433915982237,
 15036: 0.5739640213948523,
 15273: 0.973328526784575,
 15505: -0.32444284226152503,
 15590: -0.7181848464596078,
 15729: 0.13245323570650436,
 16084: 0.22941573387056174,
 16121: 0.3394414288821214,
 16223: -0.4736842105263157,
 16321: 0.8992288030258968,
 16382: -0.10495671428119793,
 16545: 0.13245323570650436,
 16725: 0.6882472016116852,
 16874: 0.13245323570650436,
 17145: -0.07647191129018727,
 17221: -0.04415107856883482,
 17393: -0.22075539284417395,
 17451: 0.05263157894736839,
 17648: 0.22941573387056174,
 17746: 0.6622661785325219,
 17873: 0.4736842105263157,
 17915: -0.9544271444636667,
 18051: -0.9365858115816941,
 18207: 0.0,
 18277: 0.3458572319330373,
 18301: -0.4736842105263157,
 18417: 0.8992288030258968,
 18490: -0.7254762501100116,
 18848: -0.512989176042577,
 19131: 0.13245323570650436,
 19464: 0.13245323570650436,
 19764: 0.43528575006600695,
 19925: 0.8919017444789035,
 19986: 0.6622661785325219,
 20134: -0.13245323570650436,
 20156: -0.4736842105263157,
 20281: 0.9271726499455306,
 20660: -0.15789473684210525,
 21259: -5.551115123125783e-17,
 21717: 0.4736842105263157,
 21819: -0.32444284226152503,
 21831: 0.8992288030258968,
 21847: 0.05263157894736839,
 22250: -0.8992288030258968,
 22326: -0.8411910241920597,
 22398: -0.1025978352085154,
 22599: 0.6622661785325219,
 22747: -0.6622661785325219,
 22769: 0.32444284226152503,
 22887: -0.3458572319330373,
 22903: 0.13245323570650436,
 22969: 0.6882472016116852,
 23230: -0.9782319760890368,
 23250: 0.6882472016116852,
 23326: nan,
 23467: -0.760885910252682,
 23590: 0.760885910252682,
 24008: 0.6295412064573487,
 24192: 0.3083035200691657,
 24214: 0.27144835701531844,
 24411: 0.3746343246326776,
 24484: 0.6882472016116852,
 24567: 0.20751433915982237,
 24585: -0.4842001247062522,
 24641: 0.20751433915982237,
 24682: -0.8143450710459554,
 24747: -0.9271726499455306,
 25502: 0.760885910252682,
 25795: -0.6882472016116852,
 26022: -0.64888568452305,
 26046: 0.6622661785325219,
 26474: 0.3746343246326776,
 26479: -0.5726562866782,
 26580: 0.870571500132014,
 27332: -0.3458572319330373,
 27388: -0.6622661785325219,
 27702: 0.6622661785325219,
 27713: 0.6882472016116852,
 28018: -0.3458572319330373,
 28203: nan,
 28216: 0.9271726499455306,
 28695: -0.7346969999683856,
 28724: -0.9233805168766386,
 28735: 0.9271726499455306,
 28821: nan,
 28946: -0.24525573579398635,
 29213: -0.973328526784575,
 29426: nan,
 29520: -0.2248723981711324,
 29592: -0.9271726499455306,
 29623: -0.34437841283691134,
 29687: 0.760885910252682,
 29860: 0.22941573387056174,
 29914: 0.6622661785325219,
 30024: -0.18731716231633877,
 30062: 0.08998425413316952,
 30079: 0.64888568452305,
 30524: 0.18731716231633877,
 30610: 0.13245323570650436,
 30658: 0.7894736842105261,
 30663: -0.6622661785325219,
 30758: nan,
 30766: -0.27144835701531844,
 31266: nan,
 31418: 0.7233393492970543,
 31436: 0.22941573387056174,
 31669: nan,
 31870: 0.38827599920817424,
 32033: -0.6882472016116852,
 32358: 0.9271726499455306,
 32407: 0.7505683356701914,
 32451: 0.4842001247062522,
 32458: -0.760885910252682,
 32459: 0.64888568452305,
 32617: 0.13245323570650436,
 32680: -0.13245323570650436,
 33188: 0.6882472016116852,
 33369: -0.9446104285307814,
 33437: -0.6882472016116852,
 33532: nan,
 33583: 0.16692446522239718,
 33699: 0.4736842105263157,
 33740: 0.7894736842105261,
 33930: 0.6882472016116852,
 34174: -0.20751433915982237,
 34302: 0.5353033790313108,
 34521: 0.64888568452305,
 34830: -0.10259783520851545,
 35085: 0.4736842105263157,
 35137: -0.22941573387056174,
 35259: 0.13245323570650436,
 35265: -0.4856618642571826,
 35318: -0.4736842105263157,
 35423: -0.760885910252682,
 35429: -0.13245323570650436,
 35585: -0.6882472016116852,
 35860: -0.8143450710459554,
 35918: -0.894736842105263,
 35964: -0.15789473684210525,
 36257: 0.8411910241920597,
 36347: 0.13245323570650436,
 36445: 0.20751433915982237,
 36631: -0.6882472016116852,
 36739: -2.7755575615628914e-17,
 36946: -0.32444284226152503,
 37528: 0.9271726499455306,
 37795: 0.20751433915982237,
 37866: -0.37463432463267765,
 38057: 0.9941348467724342,
 38151: -0.13245323570650436,
 38153: -0.20751433915982237,
 38515: -0.9271726499455306,
 38949: -0.32444284226152503,
 39014: -0.760885910252682,
 39382: -0.6882472016116852,
 39395: 0.64888568452305,
 39498: 0.38827599920817424,
 39510: -0.9810229431759452,
 39535: -0.6882472016116852,
 39593: 0.6622661785325219,
 39595: 0.7181848464596078,
 39793: -0.4736842105263157,
 39981: nan,
 39994: 0.18731716231633877,
 40007: 0.973328526784575,
 40216: 0.5739640213948523,
 40234: nan,
 40275: 0.838870492807861,
 40333: -0.1025978352085154,
 40336: -0.9271726499455306,
 40611: 0.9999999999999998,
 40794: -0.7492686492653553,
 40926: 0.15789473684210525,
 40946: -0.760885910252682,
 41468: -0.20751433915982237,
 41609: 0.3458572319330373,
 41641: 0.64888568452305,
 42052: 0.13245323570650436,
 5: 0.7559289460184544,
 120: 0.1889822365046136,
 131: 0.944911182523068,
 178: 0.8660254037844386,
 244: 0.18898223650461363,
 275: 0.7559289460184544,
 340: -0.5,
 359: 0.9449111825230679,
 506: 0.8660254037844386,
 551: -0.9999999999999998,
 620: -0.9999999999999998,
 665: -0.9999999999999998,
 673: -0.944911182523068,
 698: -2.7755575615628914e-17,
 716: nan,
 799: -0.953820966476532,
 800: 0.9999999999999998,
 807: -0.9999999999999998,
 852: nan,
 967: 0.9999999999999998,
 997: -0.970725343394151,
 1090: 0.9999999999999998,
 1127: 0.1889822365046136,
 1339: -0.18898223650461354,
 1371: -0.32732683535398854,
 1480: nan,
 1532: -0.5,
 1550: -0.9999999999999998,
 1563: -0.7559289460184544,
 1568: 0.49999999999999994,
 1585: 0.9285714285714284,
 1757: nan,
 1816: 0.49999999999999994,
 1847: 0.18898223650461363,
 1950: -0.7559289460184544,
 1980: -0.32732683535398854,
 2003: 0.18898223650461357,
 2108: -0.7559289460184544,
 2270: -0.4999999999999999,
 2423: nan,
 2514: 0.7559289460184544,
 2569: -0.49999999999999994,
 2620: 0.9999999999999998,
 2791: -0.8660254037844386,
 2854: 0.9449111825230679,
 2864: 0.49999999999999994,
 2964: 0.49999999999999994,
 2987: -0.9958705948858224,
 3052: 0.9449111825230679,
 3146: 0.5,
 3304: -0.9999999999999998,
 3334: 0.7559289460184544,
 3366: 0.9878291611472618,
 3388: -0.49999999999999994,
 3488: -0.49999999999999994,
 3533: nan,
 3651: -0.8660254037844386,
 3837: -0.9999999999999998,
 3895: -0.7559289460184544,
 3930: -0.49999999999999994,
 3967: 0.49999999999999994,
 3976: -0.6546536707079771,
 3977: nan,
 4011: -0.49999999999999994,
 4083: 0.18898223650461354,
 4124: 0.18898223650461363,
 4257: -0.7559289460184544,
 4516: 0.7559289460184544,
 4556: -0.944911182523068,
 4579: -0.49999999999999994,
 4586: 0.6546536707079771,
 4622: -0.9449111825230682,
 4734: -0.49999999999999994,
 4752: nan,
 4811: 0.4999999999999999,
 4818: 0.49999999999999994,
 4935: nan,
 4938: nan,
 5076: 0.49999999999999994,
 5159: 0.0,
 5240: 0.49999999999999994,
 5368: -0.5,
 5383: 0.1428571428571429,
 5384: 0.7559289460184544,
 5425: -0.43355498476206,
 5675: 0.49999999999999994,
 5692: -0.8660254037844387,
 5731: 0.8660254037844386,
 5767: 0.8660254037844386,
 5769: 0.8660254037844386,
 5836: -0.49999999999999994,
 5837: 0.9449111825230679,
 5852: nan,
 6044: 0.8660254037844386,
 6051: -0.944911182523068,
 6056: -0.9819805060619655,
 6065: 0.49999999999999994,
 6088: -0.5,
 6155: 0.9449111825230682,
 6198: 0.49999999999999994,
 6262: -0.6546536707079771,
 6308: -0.8660254037844386,
 6315: 0.18898223650461363,
 6439: -0.49999999999999994,
 6487: -1.0,
 6530: -1.0,
 6569: 0.0,
 6573: -0.49999999999999994,
 6592: 0.7559289460184544,
 6607: -0.1428571428571429,
 6766: -0.49999999999999994,
 6826: -0.9819805060619655,
 6979: -0.4999999999999999,
 6993: -0.9999999999999998,
 7037: 0.18898223650461363,
 7052: nan,
 7168: -0.9819805060619655,
 7185: 0.8660254037844386,
 7222: -0.7559289460184544,
 7256: -1.0,
 7311: 1.0,
 7522: 0.7559289460184544,
 7566: nan,
 7662: -0.49999999999999994,
 7691: -0.052414241836095915,
 7711: -0.9819805060619655,
 7755: -0.49999999999999994,
 7793: -0.6546536707079772,
 8030: nan,
 8308: -0.9999999999999998,
 8366: -0.49999999999999994,
 8379: -0.49999999999999994,
 8394: -0.49999999999999994,
 8414: -0.9999999999999998,
 8453: -0.49999999999999994,
 8460: 0.49999999999999994,
 8528: 0.49999999999999994,
 8529: -0.9607689228305228,
 8620: 0.9999999999999998,
 8630: 0.9897433186107871,
 8806: -0.5,
 8811: 0.0,
 8820: -0.944911182523068,
 8863: -0.9999999999999998,
 8914: 0.8660254037844386,
 8964: 0.14285714285714285,
 9012: 0.06401843996644796,
 9101: -0.8660254037844386,
 9214: 0.32732683535398854,
 9319: -0.5,
 9365: nan,
 9385: 0.9538209664765319,
 9391: 0.9819805060619655,
 9411: nan,
 9444: -0.49999999999999994,
 9702: nan,
 9751: 0.2773500981126146,
 9929: -0.7559289460184544,
 10001: 0.8660254037844386,
 10064: 0.7559289460184544,
 10119: -0.49999999999999994,
 10155: 0.18898223650461363,
 10158: -0.49999999999999994,
 10217: 0.49999999999999994,
 10364: -0.9999999999999998,
 10526: 0.0,
 10744: -0.49999999999999994,
 10813: nan,
 11107: nan,
 11138: -0.5,
 11206: -0.9285714285714285,
 11256: 0.0,
 11347: 1.0,
 11357: -0.9999999999999998,
 11399: -0.9999999999999998,
 11459: -0.7559289460184544,
 11517: 0.49999999999999994,
 11539: -0.8660254037844386,
 11584: 0.49999999999999994,
 11601: 0.8660254037844386,
 11626: -0.49999999999999994,
 11633: -0.9999999999999998,
 11665: -0.944911182523068,
 11702: 0.9819805060619655,
 11715: 0.1889822365046136,
 11764: -0.18898223650461363,
 11907: -0.7559289460184544,
 12113: -0.9449111825230679,
 12120: -1.0,
 12262: 0.9449111825230678,
 12280: -0.9449111825230679,
 12321: -0.917662935482247,
 12399: -0.18898223650461363,
 12421: -0.49999999999999994,
 12426: 0.7559289460184544,
 12504: -0.49999999999999994,
 12538: -0.49999999999999994,
 12736: -0.9449111825230679,
 12784: -0.970725343394151,
 12924: 0.9285714285714284,
 12950: -0.7559289460184544,
 12966: -0.970725343394151,
 12973: -0.944911182523068,
 13135: -0.3812464258315117,
 13154: nan,
 13325: nan,
 13399: -0.944911182523068,
 13404: 0.9449111825230679,
 13410: 0.1889822365046136,
 13411: -0.9819805060619655,
 13465: 0.0,
 13520: -0.49999999999999994,
 13523: -0.7559289460184544,
 13526: 0.7559289460184544,
 13552: 0.49999999999999994,
 13562: nan,
 13583: 0.5636214801906779,
 13670: -0.6546536707079771,
 13961: nan,
 14062: -0.49999999999999994,
 14079: -0.49999999999999994,
 14164: 0.944911182523068,
 14190: 0.9449111825230678,
 14356: 0.9999999999999998,
 14415: 0.9285714285714285,
 14545: -0.944911182523068,
 14552: -0.9449111825230679,
 14559: 0.0,
 14658: -0.9999999999999998,
 14703: 0.18898223650461363,
 14798: -0.1889822365046136,
 14815: -0.49999999999999994,
 14902: 0.6546536707079771,
 14964: -0.6286185570937121,
 15010: nan,
 15017: 1.0,
 15030: -0.49999999999999994,
 15209: 0.49999999999999994,
 15234: -0.7559289460184544,
 15248: 0.8660254037844386,
 15337: 0.4999999999999999,
 15356: nan,
 15385: -0.9819805060619655,
 15410: -0.9819805060619655,
 15434: 0.9449111825230679,
 15449: nan,
 15474: 0.9449111825230679,
 15488: -0.5,
 15638: 0.7559289460184544,
 15644: 0.0,
 15700: -0.5636214801906779,
 15795: -0.4999999999999999,
 15809: 0.9449111825230679,
 15810: -0.49999999999999994,
 15819: -0.49999999999999994,
 15938: -0.9999999999999998,
 16070: -0.7559289460184543,
 16095: -0.9449111825230678,
 16138: nan,
 16200: 0.8660254037844386,
 16272: -0.49999999999999994,
 16405: -0.8660254037844386,
 16482: -0.49999999999999994,
 16489: 1.0,
 16530: 1.0,
 16574: nan,
 16615: 0.8660254037844386,
 16661: 0.18898223650461363,
 16668: -0.7559289460184544,
 16824: 0.49999999999999994,
 16887: -0.9819805060619655,
 16905: 0.1889822365046136,
 16957: 0.8910421112136306,
 17175: -0.49999999999999994,
 17331: -0.49999999999999994,
 17413: 0.8660254037844386,
 17435: -0.6185895741317419,
 17546: nan,
 17574: -1.0,
 17877: -0.7559289460184544,
 17970: -0.4999999999999999,
 17993: 0.49999999999999994,
 18077: 0.18898223650461363,
 18153: 0.9999999999999998,
 18171: -0.6546536707079771,
 18204: 0.944911182523068,
 18257: 0.9999999999999998,
 18274: -0.7559289460184544,
 18446: 0.49999999999999994,
 18452: 0.7559289460184544,
 18473: 0.7559289460184544,
 18513: 0.7559289460184544,
 18597: 0.49999999999999994,
 18733: -0.49999999999999994,
 18743: nan,
 18805: 0.18898223650461363,
 18823: 0.0,
 18876: -0.5,
 19012: -0.49999999999999994,
 19087: 0.49999999999999994,
 19157: nan,
 19355: -0.49999999999999994,
 19637: 0.4193139346887673,
 19696: -0.18898223650461363,
 19755: 0.32732683535398854,
 19781: -0.9449111825230679,
 19795: 0.944911182523068,
 19873: -0.5,
 19951: -0.9999999999999998,
 20225: -0.5,
 20316: -0.49999999999999994,
 20439: -0.49999999999999994,
 20524: nan,
 20609: -0.8219949365267865,
 20640: nan,
 20685: -0.8357661056711407,
 20704: 0.18898223650461363,
 20788: 0.7559289460184544,
 20853: 0.5852057359806528,
 20873: 0.49999999999999994,
 20918: -0.08847479104076181,
 20947: 0.9449111825230679,
 20978: 0.18898223650461363,
 21090: -0.32732683535398854,
 21128: 0.9999999999999998,
 21148: -0.8660254037844386,
 21251: -0.6933752452815364,
 21271: 0.9999999999999998,
 21325: nan,
 21326: -0.49999999999999994,
 21374: nan,
 21383: nan,
 21433: -0.970725343394151,
 21441: 0.9999999999999998,
 21509: 0.2773500981126146,
 21635: -0.49999999999999994,
 21953: -0.7559289460184544,
 21982: -0.6933752452815364,
 22188: -0.49999999999999994,
 22310: nan,
 22374: -0.8660254037844386,
 22444: -0.49999999999999994,
 22454: -0.970725343394151,
 22561: -0.18898223650461363,
 22595: -0.49999999999999994,
 22788: 0.8660254037844386,
 22883: -0.5765566601970551,
 22946: -0.49999999999999994,
 22963: -0.9878291611472618,
 23097: -0.8660254037844386,
 23217: 0.970725343394151,
 23294: -0.32732683535398854,
 23302: nan,
 23310: 0.9999999999999998,
 23520: 0.18898223650461363,
 23565: 0.49999999999999994,
 23652: -0.9999999999999998,
 23720: 0.0,
 23721: nan,
 23789: 0.18898223650461363,
 23833: nan,
 23860: 0.18898223650461363,
 23912: 0.7559289460184544,
 23916: 0.18898223650461363,
 23948: -0.1889822365046136,
 23949: -0.21677749238103,
 23996: 0.8660254037844386,
 24063: -0.49999999999999994,
 24088: -0.9999999999999998,
 24221: 0.49999999999999994,
 24289: 0.9999999999999998,
 24409: 0.18898223650461363,
 24518: 0.9999999999999998,
 24519: 0.9999999999999998,
 24691: -0.4999999999999999,
 24874: 0.49999999999999994,
 24884: -0.49999999999999994,
 25131: -0.49999999999999994,
 25185: -0.9999999999999998,
 25213: -0.49999999999999994,
 25256: -0.9819805060619657,
 25295: 0.49999999999999994,
 25305: 0.4193139346887673,
 25326: 0.49999999999999994,
 25449: -0.18898223650461363,
 25524: 0.49999999999999994,
 25722: 0.9999999999999998,
 25740: -0.7559289460184544,
 25769: 0.7559289460184544,
 25826: 0.8660254037844386,
 25842: -0.9999999999999998,
 25880: -0.9999999999999998,
 25938: -0.5,
 25950: 0.49999999999999994,
 25968: nan,
 25980: -0.1889822365046136,
 26091: -0.7559289460184546,
 26191: 0.49999999999999994,
 26194: -0.49999999999999994,
 26218: -0.8660254037844386,
 26461: 0.7559289460184544,
 26602: -0.9607689228305228,
 26800: 0.6546536707079771,
 26833: 0.9999999999999998,
 26886: -0.944911182523068,
 26903: 0.944911182523068,
 27023: -0.6933752452815364,
 27083: nan,
 27167: nan,
 27210: -0.944911182523068,
 27451: nan,
 27494: -0.944911182523068,
 27504: nan,
 27843: -0.49999999999999994,
 27869: -0.49999999999999994,
 28085: 0.6546536707079771,
 28125: 0.9449111825230679,
 28191: -0.9999999999999998,
 28233: 0.18898223650461354,
 28246: -0.944911182523068,
 28292: nan,
 28330: -0.9819805060619657,
 28383: 1.0,
 28480: 0.7559289460184544,
 28586: -0.8660254037844386,
 28670: -0.5,
 28680: -0.944911182523068,
 28836: -0.998906107238672,
 28844: 0.9449111825230678,
 28847: -0.6546536707079771,
 28862: -0.4999999999999999,
 28938: -0.9999999999999998,
 29046: 0.0,
 29047: 0.8660254037844386,
 29100: nan,
 29185: -0.49999999999999994,
 29193: 0.9285714285714284,
 29289: -0.49999999999999994,
 29300: -0.7559289460184544,
 29342: 0.7559289460184544,
 29346: -0.8660254037844386,
 29447: -0.8660254037844386,
 29453: 0.8386278693775346,
 29489: -0.35921060405354976,
 29559: nan,
 29568: 0.18898223650461365,
 29605: -0.9999999999999998,
 29657: -1.0,
 29661: 0.0,
 29712: -0.49999999999999994,
 29831: 0.8660254037844386,
 29908: 0.18898223650461363,
 29930: -0.4999999999999999,
 29951: -0.49999999999999994,
 30053: 0.944911182523068,
 30119: 0.9999999999999998,
 30140: nan,
 30216: -0.49999999999999994,
 30335: -0.49999999999999994,
 30418: -0.49999999999999994,
 30635: -0.49999999999999994,
 30649: -0.4999999999999999,
 30721: 0.49999999999999994,

In [129]:
pearsonDF = pd.DataFrame.from_dict(pearsoncorrelationdict, orient='index')
pearsonDF.columns = ['similarityIndex']
pearsonDF['userId'] = pearsonDF.index 
pearsonDF.index = range(len(pearsonDF))
pearsonDF.head()

   similarityIndex  userId
0         1.000000       2
1        -0.838870     115
2         0.044151     128
3         0.132453     176
4        -0.052632     237

In [131]:
topUser = pearsonDF.sort_values(by='similarityIndex', ascending=False)[0:50]
topUser.head()

      similarityIndex  userId
1755              1.0   35644
1666              1.0   31593
1213              1.0   13007
1777              1.0   36679
1215              1.0   13107

In [133]:
print(topUser['userId'].dtype)
print(rating_df['userId'].dtype)

int64
int64

In [135]:
topUser['userId'] = topUser['userId'].apply(lambda x: x[0] if isinstance(x, (list, np.ndarray)) else x)
topUser['userId'] = pd.to_numeric(topUser['userId'], errors='coerce')
topUser.dropna(subset=['userId'], inplace=True)
topUser['userId'] = topUser['userId'].astype('int64')
print(topUser['userId'].dtype)

int64

In [137]:
common_ids = set(topUser['userId']).intersection(set(rating_df['userId']))
print(len(common_ids))

50

In [145]:
topUserRating = topUser.merge(rating_df, left_on='userId', right_on='userId', how='inner')
topUserRating.head()

   similarityIndex  userId  movieId  rating
0              1.0   35644        1     3.5
1              1.0   35644      296     5.0
2              1.0   35644      318     4.5
3              1.0   35644      364     5.0
4              1.0   35644      784     3.0

In [151]:
topUserRating['weightedRating'] = topUserRating['similarityIndex'] * topUserRating['rating']
topUserRating.head()

   similarityIndex  userId  movieId  rating  weightedRating
0              1.0   35644        1     3.5             3.5
1              1.0   35644      296     5.0             5.0
2              1.0   35644      318     4.5             4.5
3              1.0   35644      364     5.0             5.0
4              1.0   35644      784     3.0             3.0

In [157]:
temptopUserRating = topUserRating.groupby('movieId').sum()[['similarityIndex','weightedRating']]
temptopUserRating.columns = ['sum_similarityIndex','sum_weightedRating']
temptopUserRating.head()

         sum_similarityIndex  sum_weightedRating
movieId
1                       23.0                82.5
2                        5.0                13.5
5                        1.0                 2.5
6                        3.0                12.5
10                       4.0                12.5

In [161]:
recommendation_df = pd.DataFrame()
recommendation_df['weighted average recommendation score'] = temptopUserRating['sum_weightedRating']/temptopUserRating['sum_similarityIndex']
recommendation_df['movieId'] = temptopUserRating.index
recommendation_df.head()

         weighted average recommendation score  movieId
movieId
1                                     3.586957        1
2                                     2.700000        2
5                                     2.500000        5
6                                     4.166667        6
10                                    3.125000       10

In [163]:
recommendation_df = recommendation_df.sort_values(by='weighted average recommendation score', ascending=False)
recommendation_df.head(10)

         weighted average recommendation score  movieId
movieId
151315                                     5.0   151315
49772                                      5.0    49772
7346                                       5.0     7346
106785                                     5.0   106785
82152                                      5.0    82152
82378                                      5.0    82378
68848                                      5.0    68848
1111                                       5.0     1111
4467                                       5.0     4467
68159                                      5.0    68159

In [165]:
movies_df.loc[movies_df['movieId'].isin(recommendation_df.head(10)['movieId'].tolist())]

       movieId                                            title  year
1088      1111  Microcosmos (Microcosmos: Le peuple de l'herbe)  1996
4373      4467              Adventures of Baron Munchausen, The  1988
7235      7346                              Girl Next Door, The  2004
11519    49772                                Painted Veil, The  2006
13669    68159                                    State of Play  2009
13764    68848                              Brothers Bloom, The  2008
16300    82152                                          Beastly  2011
16356    82378                                  All Good Things  2010
22293   106785                                        Homefront  2013
34117   151315                                     Ride Along 2  2016